/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sean' at '7/6/16 7:52 AM' with Gradle 2.13
 *
 * @author sean, @date 7/6/16 7:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
